-- MySQL Script generated by MySQL Workbench
-- Mon Mar 20 11:51:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `data` ;
USE `data` ;

-- -----------------------------------------------------
-- Table `data`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`shop` (
  `id_shop` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_shop`));


-- -----------------------------------------------------
-- Table `data`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `address` VARCHAR(30) NOT NULL,
  `phone` VARCHAR(30) NOT NULL,
  `shop_id` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX (`shop_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`shop_id`)
    REFERENCES `data`.`shop` (`id_shop`));


-- -----------------------------------------------------
-- Table `data`.`good`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`good` (
  `id_good` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `count` INT NOT NULL,
  `price` INT NOT NULL,
  `category` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_good`));


-- -----------------------------------------------------
-- Table `data`.`action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`action` (
  `id_action` INT NOT NULL AUTO_INCREMENT,
  `name_good` VARCHAR(30) NOT NULL,
  `discount` INT NOT NULL,
  `price_discount` INT NOT NULL,
  `good_id` INT NOT NULL,
  PRIMARY KEY (`id_action`),
  INDEX (`good_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`good_id`)
    REFERENCES `data`.`good` (`id_good`));


-- -----------------------------------------------------
-- Table `data`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `data`.`delivery` (
  `id_delivery` INT NOT NULL AUTO_INCREMENT,
  `delivery_time` VARCHAR(30) NOT NULL,
  `price` VARCHAR(30) NOT NULL,
  `delivery_id` INT NOT NULL,
  `good_id` INT NOT NULL,
  PRIMARY KEY (`id_delivery`),
  INDEX (`delivery_id` ASC) VISIBLE,
  INDEX (`good_id` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`delivery_id`)
    REFERENCES `data`.`client` (`id_client`),
  CONSTRAINT ``
    FOREIGN KEY (`good_id`)
    REFERENCES `data`.`good` (`id_good`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
